# Site settings
title: ".emacs.d: a configuration odyssey"
author:
  name: James Kruth
  email: james@kruth.org
description: > # this means to ignore newlines until "baseurl:"
  A journal of my ongoing quest to configure emacs, a more elegant editor
  for a more civilized age.
baseurl: "/.emacs.d" # the subpath of your site, e.g. /blog/
url: "https://artlogic.github.io" # the base hostname & protocol for your site
twitter_username: artlogic
github_username:  artlogic

# Build settings
exclude: ['Gemfile', 'Gemfile.lock']

theme: minima

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

permalink: "/entry/:year/:month/:day/:title/"
timezone: America/Detroit

repository: artlogic/.emacs.d
google_analytics: UA-1196646-6

# simulate github pages
safe: true
